version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces:cached
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: /bin/sh -c "while sleep 1000; do :; done"
