FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-22.04
RUN apt update && apt upgrade -y \
    && apt-get install -y build-essential \
    && apt-get install -y git \
    && apt-get install -y iproute2 \
    && apt-get install -y iputils-ping \
    && apt-get install -y netcat-openbsd
